trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UseNode@1
  inputs:
    version: '16.x'
  displayName: 'Install Node.js'

- script: |
    npm install
  displayName: 'npm install'

- script: |
    npm run build
  displayName: 'npm build'
- task: CopyFiles@2
  inputs:
    sourceFolder: '$(Build.SourcesDirectory)'
    contents: |
       src/*
       public/*
    targetFolder: '$(Build.ArtifactStagingDirectory)'
  displayName: 'Copy project files'

- task: PublishPipelineArtifact@1
  inputs:
    artifactName: e2e-server
    targetPath: '$(Build.ArtifactStagingDirectory)'
    publishLocation: 'pipeline'
  displayName: 'Publish npm artifact'
- task: XplatGenerateReleaseNotes@4
  inputs:
    outputfile: '$(Build.ArtifactStagingDirectory)/releasenotes.md'
    outputVariableName: 'releasenotes'
    templateLocation: 'InLine'
    inlinetemplate: |
      # Notes for release  {{releaseDetails.releaseDefinition.name}}    
      **Release Number**  : {{releaseDetails.name}}
      **Release completed** : {{releaseDetails.modifiedOn}}     
      **Build Number**: {{buildDetails.id}}
      **Compared Release Number**  : {{compareReleaseDetails.name}}    
      **Build Trigger PR Number**: {{lookup buildDetails.triggerInfo 'pr.number'}} 
      
      # Associated Pull Requests ({{pullRequests.length}})
      {{#forEach pullRequests}}
      {{#if isFirst}}### Associated Pull Requests (only shown if  PR) {{/if}}
      *  **{{this.pullRequestId}}** {{this.title}}
      {{/forEach}}
      
      # Builds with associated WI/CS ({{builds.length}})
      {{#forEach builds}}
      {{#if isFirst}}## Builds {{/if}}
      -  Build {{this.build.buildNumber}}
      {{#forEach this.commits}}
         - CS {{this.id}}
            - **Message:** {{this.message}}
      {{/forEach}}
      {{#forEach this.workitems}}
         - WI {{this.id}}
            - **Title** {{lookup this.fields 'System.Title'}}
      {{/forEach}} 
      {{#forEach this.tests}}
         - Test {{this.id}} 
            -  **Name** {{this.testCase.name}}
            -  **Outcome** {{this.outcome}}
      {{/forEach}} 
      {{/forEach}}
    checkStage: true
    dumpPayloadToConsole: false
    dumpPayloadToFile: false
    replaceFile: true
    getParentsAndChildren: false
    getAllParents: false
    getIndirectPullRequests: false
    stopOnError: false
    considerPartiallySuccessfulReleases: false
    checkForManuallyLinkedWI: false
    wiqlFromTarget: 'WorkItems'
- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: '$(Build.ArtifactStagingDirectory)'
    artifactName: 'releasenotes'
    publishLocation: 'Container'